spring.application.name=Live-Board
server.port=8080

# Configuracion del modo de comunicacionn del tablero
# Opciones: rest (por defecto) o websocket
# Para cambiar a WebSockets, cambia esta linea a: board.communication.mode=websocket
board.communication.mode=rest

# Configuracion de logging
logging.level.arsw.java.Live_Board=DEBUG
logging.level.org.springframework.web.socket=DEBUG

# Configuracion de Jackson
spring.jackson.serialization.indent-output=true
